spring:
  application:
    name: bookstore

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never
      schema-locations: classpath:scripts/schema.sql
      data-locations: classpath:scripts/data.sql

  batch:
    job:
      enabled: false            # 앱 시작 시 자동 실행 방지 (스케줄러로만 실행)
    jdbc:
      initialize-schema: always # Spring Batch 메타 테이블 자동 생성

  kafka:
    bootstrap-servers: localhost:9092

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

kafka:
  topic:
    gift-promotion: book.promotion.gift

batch:
  scheduler:
    enabled: false   # true로 바꾸면 30초 배치 재활성화