-- book
INSERT INTO book (isbn, title, author, publisher, regular_price, content, thumbnail_url, published_at, created_at, updated_at) VALUES
                                                                                                                                    ('9791162242964', '클린 코드', '로버트 마틴', '인사이트', 22000, '개발', 'https://via.placeholder.com/150', '2013-12-24 00:00:00', NOW(), NOW()),
                                                                                                                                    ('9791158391201', '객체지향의 사실과 오해', '조영호', '위키북스', 18000, '개발', 'https://via.placeholder.com/150', '2015-06-17 00:00:00', NOW(), NOW()),
                                                                                                                                    ('9791162243130', '이펙티브 자바', '조슈아 블로크', '인사이트', 36000, '개발', 'https://via.placeholder.com/150', '2018-11-01 00:00:00', NOW(), NOW()),
                                                                                                                                    ('9791188621651', '도메인 주도 설계', '에릭 에반스', '위키북스', 43000, '개발', 'https://via.placeholder.com/150', '2011-07-01 00:00:00', NOW(), NOW()),
                                                                                                                                    ('9791162242988', '리팩터링', '마틴 파울러', '한빛미디어', 34000, '개발', 'https://via.placeholder.com/150', '2020-04-01 00:00:00', NOW(), NOW()),
                                                                                                                                    ('9791185873809', '가난한 아빠 부자 아빠', '로버트 기요사키', '민음인', 16800, '경제', 'https://via.placeholder.com/150', '2018-01-01 00:00:00', NOW(), NOW()),
                                                                                                                                    ('9788936434120', '채식주의자', '한강', '창비', 12000, '소설', 'https://via.placeholder.com/150', '2007-10-30 00:00:00', NOW(), NOW()),
                                                                                                                                    ('9788954651135', '아몬드', '손원평', '창비', 13800, '소설', 'https://via.placeholder.com/150', '2017-03-31 00:00:00', NOW(), NOW()),
                                                                                                                                    ('9788932920245', '82년생 김지영', '조남주', '민음사', 13000, '소설', 'https://via.placeholder.com/150', '2016-10-14 00:00:00', NOW(), NOW()),
                                                                                                                                    ('9788937460449', '어린 왕자', '생텍쥐페리', '열린책들', 9800, '소설', 'https://via.placeholder.com/150', '2015-05-20 00:00:00', NOW(), NOW());

-- bestseller_promotion (1~5위)
INSERT INTO bestseller_promotion (book_id, ranking, list_type, valid_from, valid_until, published_at, created_at) VALUES
                                                                                                                     (1, 1, '주간', '2026-05-06 00:00:00', '2026-05-12 23:59:59', NOW(), NOW()),
                                                                                                                     (3, 2, '주간', '2026-05-06 00:00:00', '2026-05-12 23:59:59', NOW(), NOW()),
                                                                                                                     (7, 3, '주간', '2026-05-06 00:00:00', '2026-05-12 23:59:59', NOW(), NOW()),
                                                                                                                     (8, 4, '주간', '2026-05-06 00:00:00', '2026-05-12 23:59:59', NOW(), NOW()),
                                                                                                                     (2, 5, '주간', '2026-05-06 00:00:00', '2026-05-12 23:59:59', NOW(), NOW());

-- discount_promotion
INSERT INTO discount_promotion (book_id, discount_rate, discounted_price, valid_from, valid_until, published_at, created_at) VALUES
                                                                                                                                 (1, 10, 19800, '2026-05-01 00:00:00', '2026-05-31 23:59:59', NOW(), NOW()),
                                                                                                                                 (3, 15, 30600, '2026-05-01 00:00:00', '2026-05-31 23:59:59', NOW(), NOW()),
                                                                                                                                 (5, 20, 27200, '2026-05-01 00:00:00', '2026-05-31 23:59:59', NOW(), NOW()),
                                                                                                                                 (9, 10, 11700, '2026-05-01 00:00:00', '2026-05-31 23:59:59', NOW(), NOW());

-- gift_promotion (선착순 증정 — remaining_quantity 낮게 설정해서 정합성 깨짐 시나리오용)
INSERT INTO gift_promotion (book_id, gift_name, total_quantity, remaining_quantity, status, valid_from, valid_until, published_at, created_at, updated_at) VALUES
                                                                                                                                                               (2, '에코백 증정', 50, 3, 'ACTIVE', '2026-05-01 00:00:00', '2026-05-31 23:59:59', NOW(), NOW(), NOW()),
                                                                                                                                                               (4, '북마크 세트 증정', 30, 0, 'SOLD_OUT', '2026-05-01 00:00:00', '2026-05-31 23:59:59', NOW(), NOW(), NOW()),
                                                                                                                                                               (7, '친필 사인 증정', 10, 7, 'ACTIVE', '2026-05-01 00:00:00', '2026-05-31 23:59:59', NOW(), NOW(), NOW());

-- book_display_info (배치가 집계한 전시 데이터 — 배치 방식 시뮬레이션)
INSERT INTO book_display_info (book_id, has_bestseller_tag, bestseller_rank, has_discount_tag, discount_rate, display_price, has_gift_tag, gift_status, gift_remaining_qty, data_source, last_synced_at, created_at, updated_at) VALUES
                                                                                                                                                                                                                                     (1,  1, 1, 1, 10, 19800, 0, NULL, NULL,  'BATCH', NOW(), NOW(), NOW()),
                                                                                                                                                                                                                                     (2,  1, 5, 0, NULL, 18000, 1, 'ACTIVE', 3, 'BATCH', NOW(), NOW(), NOW()),
                                                                                                                                                                                                                                     (3,  1, 2, 1, 15, 30600, 0, NULL, NULL,  'BATCH', NOW(), NOW(), NOW()),
                                                                                                                                                                                                                                     (4,  0, NULL, 0, NULL, 43000, 1, 'ACTIVE', 0, 'BATCH', NOW(), NOW(), NOW()),  -- ← 핵심 정합성 문제! display는 ACTIVE인데 실제 remaining=0
                                                                                                                                                                                                                                     (5,  0, NULL, 1, 20, 27200, 0, NULL, NULL,  'BATCH', NOW(), NOW(), NOW()),
                                                                                                                                                                                                                                     (6,  0, NULL, 0, NULL, 16800, 0, NULL, NULL, 'BATCH', NOW(), NOW(), NOW()),
                                                                                                                                                                                                                                     (7,  1, 3, 0, NULL, 12000, 1, 'ACTIVE', 7, 'BATCH', NOW(), NOW(), NOW()),
                                                                                                                                                                                                                                     (8,  1, 4, 0, NULL, 13800, 0, NULL, NULL,  'BATCH', NOW(), NOW(), NOW()),
                                                                                                                                                                                                                                     (9,  0, NULL, 1, 10, 11700, 0, NULL, NULL,  'BATCH', NOW(), NOW(), NOW()),
                                                                                                                                                                                                                                     (10, 0, NULL, 0, NULL, 9800,  0, NULL, NULL, 'BATCH', NOW(), NOW(), NOW());